#!/data/data/com.termux/files/usr/bin/env zsh

for f in "$@" ; do
  if [ -f $f ] ; then
    case "$f" in
      *.tar.bz2)
        tar xvjf "$f" ;;
      *.tar.gz)
        tar xvzf "$f" ;;
      *.bz2)
        bunzip2 "$f"  ;;
      *.rar|*.cbr)
        unrar x "$f"  ;;
      *.tar.zst)
        tar --zstd -xf "$f" ;;
      *.gz|*.zz)
        unpigz "$f"   ;;
      *.gz)
        gunzip "$f"   ;;
      *.zst)
        unzstd "$f"   ;;
      *.tar.xz)
        tar xJf "$f"  ;;
      *.tar)
        tar xvf "$f"  ;;
      *.tbz2)
        tar xvjf "$f" ;;
      *.tgz)
        tar xvzf "$f" ;;
      *.zip|*.cbz|*.jar)
        unzip "$f"    ;;
      *.xz)
        unxz "$f"     ;;
      *.Z)
        uncompress "$f" ;;
      *.7z)
        7z x "$f"     ;;
      *.deb) $PREFIX/usr/bin/ar vx "$f" ;;
      *) echo "$fg_bold[green]$0: $fg[red]$f $fg_bold[yellow]cannot be extracted!" >&2 ; return 2;;
    esac
  else
    echo "$fg_bold[green]$0: $fg[red]$f $fg_bold[yellow]is not a valid file" >&2 ; return 1
  fi
done
